# Generated by Django 4.2.4 on 2023-10-18 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_version_product'),
        ('users', '0003_user_confirmation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='owner_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.product', verbose_name='Создатель продукта'),
        ),
    ]
