# Generated by Django 4.2.4 on 2023-10-18 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_owner_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='owner_product',
        ),
    ]
