# Generated by Django 4.2.4 on 2023-10-18 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0006_alter_version_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='owner_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Создатель продукта'),
        ),
    ]
